export const TERM_IDS = [
  'ahi',
  'severity',
  'oai',
  'cai',
  'hi',
  'rera',
  'obstructiveApnea',
  'clearAirway',
  'hypopnea',
  'periodicBreathing',
  'usage',
  'epr',
  'ramp',
  'maskPressure',
  'therapyPressure',
  'expiratoryPressure',
  'targetEpap',
  'leak',
  'largeLeak',
  'flow',
  'flowLimitation',
  'respiratoryRate',
  'tidalVolume',
  'minuteVentilation',
  'snore',
  'oxygenSaturation',
  'pulse',
  'median',
  'percentile95',
  'timeAtPressure',
  'eprFullTime',
] as const

export type TermId = (typeof TERM_IDS)[number]
